### ISSUE TITLE
Match History: Shuffle - Optional Breakdown per Game

### ISSUE THREAD

**Issue by derfloh205** [derfloh205/PvPLookup#45]
![image](https://github.com/derfloh205/PvPAssistant/assets/9341090/353f9c1f-2de9-4c49-bcb1-ddc11cb5791d)
->
![image](https://github.com/derfloh205/PvPAssistant/assets/9341090/9fc196d7-6f15-4936-89fc-1b9d6b40b1bf)

Gather data per individual shuffle match and make all matches displayable

e.g. by making a collapseable/uncollapseable framelist row or via popup

**Comment by Thekinghim** [comment]
I Would say that this is very high priority. As we are the only ones on the market that has this idea in mind

**Comment by Thekinghim** [comment]
I got like 48 errors it poped up when i joined a arena game and it was a lot of "bad arugment" etc and the C stack

**Comment by derfloh205** [comment]
can u remove the lines 281 to 284 here
https://github.com/derfloh205/PvPAssistant/blob/main/Util%2FDataCollection.lua#L281-L284

**Comment by derfloh205** [comment]
or on top of the file u can also remove the event in the CreateRegistreeForEvents function

I suppose that creates the error

**Comment by Thekinghim** [comment]
@iam3yal
